### ISSUE TITLE
Filter lakes that are sent in daily message

### ISSUE THREAD

**Issue by BjoernPetersen** [woog-life/telegram-bot#24]
The daily digest is getting quite spammy. Let's exclude some lakes that are currently not relevant (Santander, Havel, Heraklion, maybe Cuxhaven)

**Comment by torbencarstens** [comment]
I've created a poll to let _the people_ decide
I'd say we leave it up for a couple of days and follow up on this then.

**Comment by torbencarstens** [comment]
I've exluded the following lakes which had 2 votes each (I assume that @FelixGail had a similar strategy as I did -> voting for everything simply to see the outcome (since _somebody_ forgot to include a "IDC" option))

- Santander
- Potsdam
- Heraklion
- Sorrento

https://github.com/woog-life/telegram-bot/blob/main/values.yaml#L53

We can include Sorrento again next september.
